[package]
name = "roguelike-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.7"
ggez = "0.8.1"
image = "0.24.4"
rand = "0.8.5"
rand_seeder = "0.2.3"

